line.bot:
#  channel-token: 'xxx'
#  channel-secret: 'xxx'
  handler.path: /callback

event.handler:
  queue.capacity: 8
  thread.count: 2

logging:
  level:
    ROOT: INFO
    tw.bjn.pg: DEBUG
  pattern:
    console: '%d{"yyyy:MM:dd HH:mm:ss,SSS"} [%5p] [%t] \(%F:%M:%L\) %msg%n'

#spring:
#  datasource:
#    url: ${JDBC_DATABASE_URL}
#    username: ${JDBC_DATABASE_USERNAME}
#    password: ${JDBC_DATABASE_PASSWORD}
